name: Test & Deploy on Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.19.0]

    steps:
      - uses: actions/checkout@v2
        
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Frontend testing
        working-directory: ./frontend
        run: npm install && npm install -D && npm run test:ci
      
      - name: Backend testing
        working-directory: ./backend
        run: npm install && npm install -D && npm test
        
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "coffaine-sales"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
